#!/bin/sh
    
  start() {
    printf "Starting IP Announcement: "
    start-stop-daemon -S -q -m -b -p /var/run/announced.pid \
              -x /usr/bin/announced.sh
              [ $? = 0 ] && echo "OK" || echo "FAIL"
  }
    
  stop() {
    printf "Stopping IP Announcement: "
    start-stop-daemon -K -s SIGKILL -q -p /var/run/announced.pid \
            [ $? = 0 ] && echo "OK" || echo "FAIL"
  }
    
  case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
    *)
      echo "Usage: $0 {start|stop|restart}"
      exit 1
  esac
  
  exit $?
